#!/bin/sh

# Check dependencies
type wget > /dev/null || exit 0
type jq > /dev/null || exit 0

wget -q ipinfo.io -O - 2> /dev/null \
    | jq -r "to_entries|map(\"\(.key)=\(.value|tostring)\")|.[]" || exit 0
